from django.urls import path
from . import views

app_name = "mainapp"

urlpatterns = [
    path('', views.anasayfa, name='anasayfa'),
    path('hakkimda-dr-ersin-aydin/', views.hakkimda, name='hakkimda'),
    path('basinda-dr-ersin-aydin/', views.basinda, name='basinda'),
    path('egitim-dr-ersin-aydin/', views.egitim, name='egitim'),
    path('iletisim/', views.iletisim, name='iletisim'),
    path('danisan-gorusleri-ve-yorumlari/', views.danisan_yorum, name='danisan_yorum'),
    path('estetik-kozmetik-ve-genel-dermatoloji-cilt-hastaliklari/', views.uygulamalar, name='uygulamalar'),
    path('estetik-kozmetik-ve-genel-dermatoloji-cilt-hastaliklari/kirisiklik-tedavisi/', views.uygulamalar2, name='uygulamalar2'),
    path('estetik-kozmetik-ve-genel-dermatoloji-cilt-hastaliklari/el-ve-koltuk-alti-terleme-tedavisi/', views.uygulamalar3, name='uygulamalar3'),
    path('estetik-kozmetik-ve-genel-dermatoloji-cilt-hastaliklari/somon-dna-asisi/', views.uygulamalar4, name='uygulamalar4'),
    path('estetik-kozmetik-ve-genel-dermatoloji-cilt-hastaliklari/aquapeel/', views.uygulamalar5, name='uygulamalar5'),
    path('estetik-kozmetik-ve-genel-dermatoloji-cilt-hastaliklari/akne-sivilce/', views.uygulamalar6, name='uygulamalar6'),
    path('estetik-kozmetik-ve-genel-dermatoloji-cilt-hastaliklari/genital-sigil/', views.uygulamalar7, name='uygulamalar7'),
    path('estetik-kozmetik-ve-genel-dermatoloji-cilt-hastaliklari/mantar-hastaliklari/', views.uygulamalar8, name='uygulamalar8'),
    path('estetik-kozmetik-ve-genel-dermatoloji-cilt-hastaliklari/lazer-uygulamalari/', views.uygulamalar9, name='uygulamalar9'),
    path('estetik-kozmetik-ve-genel-dermatoloji-cilt-hastaliklari/cosmelan-dermamelan-leke-tedavisi/', views.uygulamalar10, name='uygulamalar10'),
    path('estetik-kozmetik-ve-genel-dermatoloji-cilt-hastaliklari/peeling/', views.uygulamalar11, name='uygulamalar11'),
    path('estetik-kozmetik-ve-genel-dermatoloji-cilt-hastaliklari/dis-sikma-tedavisi/', views.uygulamalar12, name='uygulamalar12'),
    path('estetik-kozmetik-ve-genel-dermatoloji-cilt-hastaliklari/ip-uygulamasi/', views.uygulamalar13, name='uygulamalar13'),
    path('estetik-kozmetik-ve-genel-dermatoloji-cilt-hastaliklari/dolgu-uygulamalari/', views.uygulamalar14, name='uygulamalar14'),
    path('estetik-kozmetik-ve-genel-dermatoloji-cilt-hastaliklari/sac-mezoterapisi/', views.uygulamalar15, name='uygulamalar15'),
    path('estetik-kozmetik-ve-genel-dermatoloji-cilt-hastaliklari/fraksiyonel-radyofrekans-altin-igne/', views.uygulamalar16, name='uygulamalar16'),
    path('estetik-kozmetik-ve-genel-dermatoloji-cilt-hastaliklari/roller-ve-dermapen/', views.uygulamalar17, name='uygulamalar17'),
    path('estetik-kozmetik-ve-genel-dermatoloji-cilt-hastaliklari/prp-platelet-rich-plasma/', views.uygulamalar18, name='uygulamalar18'),
    path('estetik-kozmetik-ve-genel-dermatoloji-cilt-hastaliklari/cilt-bakimi/', views.uygulamalar19, name='uygulamalar19'),
    path('estetik-kozmetik-ve-genel-dermatoloji-cilt-hastaliklari/mezoterapi/', views.uygulamalar20, name='uygulamalar20'),
    path('estetik-kozmetik-ve-genel-dermatoloji-cilt-hastaliklari/leke-tedavisi/', views.uygulamalar21, name='uygulamalar21'),
    path('estetik-kozmetik-ve-genel-dermatoloji-cilt-hastaliklari/behcet-hastaligi/', views.uygulamalar22, name='uygulamalar22'),
    path('estetik-kozmetik-ve-genel-dermatoloji-cilt-hastaliklari/cinsel-yolla-bulasan-hastaliklar/', views.uygulamalar23, name='uygulamalar23'),
    path('estetik-kozmetik-ve-genel-dermatoloji-cilt-hastaliklari/cilt-benleri/', views.uygulamalar24, name='uygulamalar24'),
    path('estetik-kozmetik-ve-genel-dermatoloji-cilt-hastaliklari/cilt-kanserleri/', views.uygulamalar25, name='uygulamalar25'),
    path('estetik-kozmetik-ve-genel-dermatoloji-cilt-hastaliklari/ekzema/', views.uygulamalar26, name='uygulamalar26'),
    path('estetik-kozmetik-ve-genel-dermatoloji-cilt-hastaliklari/sigil-verru/', views.uygulamalar27, name='uygulamalar27'),
    path('estetik-kozmetik-ve-genel-dermatoloji-cilt-hastaliklari/urtiker-kurdesen/', views.uygulamalar28, name='uygulamalar28'),
    path('estetik-kozmetik-ve-genel-dermatoloji-cilt-hastaliklari/gunesten-korunma/', views.uygulamalar29, name='uygulamalar29'),
    path('estetik-kozmetik-ve-genel-dermatoloji-cilt-hastaliklari/herpes-simpleks-enfeksiyonu-ucuk/', views.uygulamalar30, name='uygulamalar30'),
    path('estetik-kozmetik-ve-genel-dermatoloji-cilt-hastaliklari/hiperhidrozis-asiri-terleme/', views.uygulamalar31, name='uygulamalar31'),
    path('estetik-kozmetik-ve-genel-dermatoloji-cilt-hastaliklari/hipertrofik-skar-keloid/', views.uygulamalar32, name='uygulamalar32'),
    path('estetik-kozmetik-ve-genel-dermatoloji-cilt-hastaliklari/liken-planus/', views.uygulamalar33, name='uygulamalar33'),
    path('estetik-kozmetik-ve-genel-dermatoloji-cilt-hastaliklari/tirnak-hastaliklari/', views.uygulamalar34, name='uygulamalar34'),
    path('estetik-kozmetik-ve-genel-dermatoloji-cilt-hastaliklari/vitiligo/', views.uygulamalar35, name='uygulamalar35'),
    path('estetik-kozmetik-ve-genel-dermatoloji-cilt-hastaliklari/pitriazis-rosea/', views.uygulamalar36, name='uygulamalar36'),
    path('estetik-kozmetik-ve-genel-dermatoloji-cilt-hastaliklari/psoriazis-sedef-hastaligi/', views.uygulamalar37, name='uygulamalar37'),
    path('estetik-kozmetik-ve-genel-dermatoloji-cilt-hastaliklari/roza-hastaligi-gul-hastaligi-gulleme/', views.uygulamalar38, name='uygulamalar38'),
    path('estetik-kozmetik-ve-genel-dermatoloji-cilt-hastaliklari/sac-hastaliklari/', views.uygulamalar39, name='uygulamalar39'),
    path('estetik-kozmetik-ve-genel-dermatoloji-cilt-hastaliklari/sac-dokulmesi/', views.uygulamalar40, name='uygulamalar40'),
    path('estetik-kozmetik-ve-genel-dermatoloji-cilt-hastaliklari/zona-zoster-gece-yanigi/', views.uygulamalar41, name='uygulamalar41'),
]
