# Generated by Django 2.2.15 on 2020-08-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='iletisim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(help_text='Lütfen İsminizi Yazınız', max_length=200)),
                ('soy_isim', models.CharField(help_text='Lütfen Soyisminizi Yazınız', max_length=200)),
                ('eposta', models.EmailField(help_text='Lütfen Eposta Adresinizi Yazınız.', max_length=200)),
                ('telefon', models.CharField(help_text='Telefon numaranızı giriniz', max_length=50)),
                ('mesaj', models.TextField(help_text='Mesajınızı yazınız')),
                ('geri_donus', models.BooleanField(default=False, help_text='Cevap verilen mesajlar true yapılacak')),
                ('cevap', models.TextField(help_text='Cevap metni buraya yazılacak', null=True)),
                ('kayit_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
